controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

token_refresh:
    path: /api/token/refresh
    controller: App\Controller\TokenController::refreshToken
    methods: POST

token_payload:
    path: /api/token/payload
    controller: App\Controller\TokenController::getTokenPayload
    methods: GET

api_token_check:
    path: /api/token/check/{id}
    controller: App\Controller\TokenController::getTokens
    methods: GET
